---

- hosts: webserver

  become: true


  tasks:

    - name: Install puppet
      shell: |
        wget https://apt.puppetlabs.com/puppet6-release-focal.deb
        sudo dpkg -i puppet6-release-focal.deb
        sudo apt-get update -y
        sudo apt-get install puppet-agent -y
        
      register: command_output
    - debug:
        var: command_output.stdout_lines
